version: '3'

networks:
  default-network:
    driver: bridge
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - default-network
    ports:
      - "3306:3306"